#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# 반드시 미리 다음 명령을 실행해두어야함
# chmod +x ./.husky/pre-commit
# 그렇지 않으면 다음과 같은 경고가 나오고 훅이 동작하지 않음
# hint: The 'client/.husky/pre-push' hook was ignored because it's not set as executable.

cd ./client

# cd ./client/
yarn lint-staged
echo "pwd: $(pwd)"
