###
curl --location --request POST 'https://api.aurastamp.com/encode' \
--form 'model_name="the"' \
--form 'text="this is the message"' \
--form 'file=@"/C:/Users/thilllon/Downloads/aurastamp_1679106807647.png"' \
--form 'return_type="base64"'


###
curl --location --request POST 'https://api.aurastamp.com/encode' --form 'model_name="the"' --form 'text="this is the message"' --form 'file=@"/C:/Users/thilllon/Downloads/aurastamp_1679106807647.png"' --form 'return_type="base64"'
